- name: PHP (Install core and modules)
  apt: pkg={{item}} state=latest
  with_items:
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-mysqli
    - php5-mcrypt
    - php5-curl
    - php5-intl
    - php5-json

- name: PHP (Enable Modules)
  command: php5enmod {{ item }}
  with_items:
    - mcrypt
    - json
  notify: restart php-fpm

- name: PHP (Configure FPM Pool)
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf line="user = oparl" regexp="user = "
  notify: restart php-fpm

- name: PHP (Disable OPCache for CLI)
  lineinfile: dest=/etc/php5/cli/php.ini line="opcache.enable=0" regexp=";opcache\.enable="

- name: Composer (Install)
  shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: Composer (Selfupdate)
  command: composer selfupdate

- name: Bower & Gulp
  npm: name={{item}} global=yes state=latest
  with_items:
    - bower
    - gulp

- name: Sass
  gem: name=sass state=latest

- name: Nginx (Disable default website)
  file: path=/etc/nginx/sites-enabled/default state=absent
