- name: PHP
  apt: pkg={{item}} state=latest
  with_items:
    - php5-mcrypt
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-intl
    - php5-json

- name: PHP (Configure FPM Pool)
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf line="user = oparl" regexp="user = "

- name: Composer (Install)
  shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: Composer (Selfupdate)
  command: composer selfupdate

- name: Bower & Gulp
  npm: name={{item}} global=yes state=latest
  with_items:
    - bower
    - gulp

- name: Sass
  gem: name=sass state=latest
