---
- hosts: all

  tasks:
      - name: Core dependencies
        apt: pkg={{item}} state=latest update_cache=yes
        with_items:
          - language-pack-de
          - mosh
          - vim
          - nginx
          - mysql-server
          - redis-server
          - supervisor
          - anacron
          - logrotate
          - ruby
          - python
          - zip
          - unzip
          - git-core
          - texlive-base
          - node
          - npm

      - name: Copy .bashrc
        copy: src=templates/bashrc dest=/root/.bashrc force=yes

      - name: Copy .vimrc
        copy: src=templates/vimrc dest=/root/.vimrc

      - name: Buildkite Agent (Get sources.list)
        shell: echo deb https://apt.buildkite.com/buildkite-agent unstable main > /etc/apt/sources.list.d/buildkite-agent.list
        args:
          creates: /etc/apt/sources.list.d/buildkite-agent.list

      - name: Buildkite Agent (Add apt key)
        apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=32A37959C2FA5C3C99EFBC32A79206696452D198

      - name: Buildkite Agent (Install)
        apt: pkg=buildkite-agent state=latest update_cache=yes

      - name: Buildkite Agent (Set Token)
        lineinfile: dest=/etc/buildkite-agent/buildkite-agent.cfg regexp='token=' line='token="{{agent_buildkite_token}}"'

      - name: Buildkite Agent (Set Metadata)
        lineinfile: dest=/etc/buildkite-agent/buildkite-agent.cfg line="meta-data=oparl-buildserver=true"

      - name: Buildkite Agent (Run Service)
        service: name=buildkite-agent state=restarted

      - name: PHP
        apt: pkg={{item}} state=latest
        with_items:
          - php5-mcrypt
          - php5-cli
          - php5-curl
          - php5-fpm
          - php5-intl
          - php5-json

      - name: PHP (Configure FPM Pool)
        lineinfile: dest=/etc/php5/fpm/pool.d/www.conf line="user = oparl" regexp="user = "

      - name: Composer (Install)
        shell: curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
        args:
          creates: /usr/local/bin/composer

      - name: Composer (Selfupdate)
        command: composer selfupdate

      - name: Bower & Gulp
        npm: name={{item}} global=yes state=latest
        with_items:
          - bower
          - gulp

      - name: Sass
        gem: name=sass state=latest

      - name: Pandoc (Get deb)
        get_url:
          url=https://github.com/jgm/pandoc/releases/download/1.15/pandoc-1.15-1-amd64.deb
          dest=/root/pandoc.deb

      - name: Pandoc (Install)
        apt: deb=/root/pandoc.deb

      - name: Pandoc (Remove deb)
        command: rm /root/pandoc.deb

      - name: Add OParl User
        user: name=oparl groups=www-data

      - name: Demoserver (Initial Checkout)
        shell: git clone https://github.com/OParl/php-server.git demoserver && rm -rf /home/oparl/demoserver/.git
        become: yes
        become_user: oparl
        args:
          creates: /home/oparl/demoserver

      - name: Demoserver (Hosts file)
        lineinfile: dest=/etc/hosts line='46.101.250.185 demoserver.oparl.meanderingsoul.com'
