---
- hosts: all
  vars_files:
    - vars.yml
  roles:
    - system
    - {
        role: kamaln7.swapfile,
        swapfile_size: 1GiB
      }
    - buildkite
    - pandoc
    - laravel
    - {
        role: website,
        website_git_url: "{{ sites.demoserver.git }}",
        website_name: demoserver,
        website_hostname: "{{ sites.demoserver.hostname }}",
      }
    - {
        role: website,
        website_git_url: "{{ sites.spec.git }}",
        website_name: spec,
        website_hostname: "{{ sites.spec.hostname }}",
      }
