- name: Core dependencies
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - language-pack-de
    - mosh
    - vim
    - nginx
    - mysql-server
    - redis-server
    - supervisor
    - anacron
    - logrotate
    - ruby
    - python
    - python-pip
    - python-mysqldb
    - zip
    - unzip
    - git-core
    - texlive-base
    - node
    - npm

- name: Copy .bashrc
  copy: src=bashrc dest=/root/.bashrc force=yes

- name: Copy .vimrc
  copy: src=vimrc dest=/root/.vimrc force=yes

- name: Copy .bashrc to user skeleton
  copy: src=bashrc dest=/etc/skel/.bashrc force=yes

- name: Copy .vimrc to user skeleton
  copy: src=vimrc dest=/etc/skel/.vimrc force=yes

- name: Add OParl User
  user: name=oparl groups=www-data
