- name: Pandoc (Get deb)
  get_url:
    url=https://github.com/jgm/pandoc/releases/download/1.15/pandoc-1.15-1-amd64.deb
    dest=/root/pandoc.deb

- name: Pandoc (Install)
  apt: deb=/root/pandoc.deb

- name: Pandoc (Remove deb)
  command: rm /root/pandoc.deb
  args:
    removes: /root/pandoc.deb
